// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import GalleryFilterController from "./gallery_filter_controller"
application.register("gallery-filter", GalleryFilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PlayerFilterController from "./player_filter_controller"
application.register("player-filter", PlayerFilterController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
